`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Module name: my_uart_tx
// Description: UART transmitter, 8N1 format (8 data bits, no parity, 1 stop bit)
//   a wr_en pulse latches the data and serialises it LSB first:
//   start bit (low) -> D0~D7 -> stop bit (high); tx_busy stays high while transmitting.
//
// Ports:
//   clk       - system clock (50MHz)
//   rst_n     - asynchronous reset, active low
//   data[7:0] - 8-bit parallel data to transmit
//   wr_en     - write-enable pulse; its rising edge latches data and starts transmission
//   uart_tx   - UART serial transmit output pin
//   tx_busy   - transmit busy flag, high while transmitting
//   clk_bps   - baud-rate timing pulse input (generated by speed_setting)
//   bps_start - baud-rate generator start output; counting is enabled while high
//////////////////////////////////////////////////////////////////////////////////
module my_uart_tx(
				input clk,
				input rst_n,
				input[7:0] data,
				input wr_en,
				output uart_tx,
				output tx_busy,
				input clk_bps,
				output bps_start
    );

// ========== Transmit control and data latching ==========
reg[7:0]tx_data;      // latched data to transmit
reg bps_start_r;      // baud-rate generator enable register
reg tx_en;            // transmit enable (the internal signal behind tx_busy)
reg[3:0]num;          // bit counter: 0 = start bit, 1~8 = data bits, 9 = stop bit, 10 = transmission complete

// on each wr_en pulse: latch the data, start the baud-rate generator, set the transmit enable
// when num reaches 10: stop the baud-rate generator and clear the transmit enable
always @ (posedge clk or negedge rst_n)
	if(!rst_n)begin
		bps_start_r <= 1'b0;
		tx_en <= 1'b0;
		tx_data <= 8'd0;
	end

	else if(wr_en)begin             // write enable asserted, start a frame
		bps_start_r <= 1'b1;
		tx_data <= data;            // latch the parallel data
		tx_en <= 1'b1;
	end

	else if(num==4'd10)begin        // the whole frame has been sent
		bps_start_r <= 1'b0;
		tx_en <= 1'b0;
	end

assign bps_start = bps_start_r;

// ========== Serial data output ==========
reg uart_tx_r;                      // register holding the current tx pin level

always @ (posedge clk or negedge rst_n)
	if(!rst_n)begin
		num <=4'd0;
		uart_tx_r <= 1'b1;          // the idle level is high
	end

	else if(tx_en)begin             // while the transmit enable is active
		if(clk_bps)begin            // every baud-rate pulse advances to the next bit
			num <= num+1'b1;
			case(num)
			4'd0:uart_tx_r <= 1'b0;         // start bit: drive low
			4'd1:uart_tx_r <= tx_data[0];   // D0 (LSB)
			4'd2:uart_tx_r <= tx_data[1];   // D1
			4'd3:uart_tx_r <= tx_data[2];   // D2
			4'd4:uart_tx_r <= tx_data[3];   // D3
			4'd5:uart_tx_r <= tx_data[4];   // D4
			4'd6:uart_tx_r <= tx_data[5];   // D5
			4'd7:uart_tx_r <= tx_data[6];   // D6
			4'd8:uart_tx_r <= tx_data[7];   // D7 (MSB)
			4'd9:uart_tx_r <= 1'b1;         // stop bit: drive high
			default:uart_tx_r <= 1'b1;      // stays high by default (idle)
			endcase
		end
		else if(num==4'd10)num <= 4'd0;     // clear the counter, ready for the next transmission

	end
assign uart_tx = uart_tx_r;	            // output the current bit level
assign  tx_busy = tx_en;                   // transmit busy signal = transmit enable
endmodule
