`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Module name: my_uart_rx
// Description: UART receiver, 8N1 format (8 data bits, no parity, 1 stop bit)
//   a 4-stage shift register removes metastability and filters glitches, data is sampled at the midpoint of each bit,
//   receives one complete byte, LSB first.
//
// Ports:
//   clk       - system clock (50MHz)
//   rst_n     - asynchronous reset, active low
//   uart_rx   - UART serial receive input pin
//   rx_data   - 8-bit data output once reception completes
//   rx_int    - receive busy flag, high while receiving (can serve as an external busy signal)
//   clk_bps   - baud-rate sampling pulse input (generated by speed_setting at the bit midpoint)
//   bps_start - baud-rate generator start output; counting is enabled while high
//////////////////////////////////////////////////////////////////////////////////

module my_uart_rx(
		input clk,
		input rst_n,
		input uart_rx,
		output[7:0] rx_data,
		output reg rx_int,
		input clk_bps,
		output bps_start
    );

// ========== Start bit falling-edge detection ==========
// 4-stage shift register: uart_rx -> rx0 -> rx1 -> rx2 -> rx3
// Purpose: the first two stages (rx0, rx1) remove metastability across clock domains;
//       the last two stages (rx2, rx3) filter glitches together with the first two,
//       so two consecutive high samples followed by two consecutive low samples are required before a falling edge counts.
reg uart_rx0,uart_rx1,uart_rx2,uart_rx3;
wire neg_uart_rx;

always @ (posedge clk or negedge rst_n)
	if(!rst_n)begin
		uart_rx0 <= 1'b0;
		uart_rx1 <= 1'b0;
		uart_rx2 <= 1'b0;
		uart_rx3 <= 1'b0;
	end

	else begin
		uart_rx0 <= uart_rx;
		uart_rx1 <= uart_rx0;
		uart_rx2 <= uart_rx1;
		uart_rx3 <= uart_rx2;
	end

// falling-edge detection: rx3 & rx2 high (previous idle level) and rx1 & rx0 low (start bit arriving)
assign neg_uart_rx = uart_rx3 & uart_rx2 & ~uart_rx1 & ~uart_rx0;

// ========== Receive control logic ==========
reg bps_start_r;
reg[3:0] num;          // bit counter: 0 = start bit, 1~8 = data bits, 9 = stop bit


// bps_start_r: baud-rate generator enable, set when a start bit is detected, cleared after the stop bit is received
// rx_int:      receive busy flag, in step with bps_start_r, high while reception is in progress
always @ (posedge clk or negedge rst_n)
	if(!rst_n)begin
		bps_start_r <= 1'b0;
		rx_int <= 1'b0;
	end

	else if(neg_uart_rx)begin       // start bit falling edge detected, begin reception
		bps_start_r <= 1'b1;
		rx_int <= 1'b1;
	end

	else if(num==4'd9)begin         // counting to 9 (stop bit) ends reception
		bps_start_r <= 1'b0;
		rx_int <= 1'b0;
	end

assign bps_start = bps_start_r;

// ========== Data sampling and latching ==========
reg[7:0] rx_data_r;       // final received data register
reg[7:0] rx_temp_data;    // temporary buffer for the bits sampled so far

always @ (posedge clk or negedge rst_n)
	if(!rst_n)begin
		rx_temp_data <= 8'd0;
		num <= 4'd0;
		rx_data_r <= 8'd0;
	end

	else if(rx_int)begin            // only processed while reception is busy
		if(clk_bps)begin            // baud-rate sampling pulse arrives (bit midpoint)
			num <= num+1'b1;
			case(num)
			// num=0 samples the start bit and is ignored; num=1~8 sample D0~D7 in order (LSB first)
			4'd1:rx_temp_data[0] <= uart_rx;
			4'd2:rx_temp_data[1] <= uart_rx;
			4'd3:rx_temp_data[2] <= uart_rx;
			4'd4:rx_temp_data[3] <= uart_rx;
			4'd5:rx_temp_data[4] <= uart_rx;
			4'd6:rx_temp_data[5] <= uart_rx;
			4'd7:rx_temp_data[6] <= uart_rx;
			4'd8:rx_temp_data[7] <= uart_rx;
			default:;
			endcase
		end

		else if(num==4'd9)begin     // the stop bit has been sampled, latch the complete byte
			num<=4'd0;
			rx_data_r <= rx_temp_data;
		end

	end

assign rx_data = rx_data_r;

endmodule



















